export const studentsDetails = [
  {
    id: 1,
    firstName: "Martin",
    lastName: "Dubois",
    birthDate: "2002-03-15",
    email: "martin.dubois@ecole.fr",
    major: "Informatique",
  },
  {
    id: 2,
    firstName: "Sophie",
    lastName: "Laurent",
    birthDate: "2003-07-22",
    email: "sophie.laurent@ecole.fr",
    major: "Design UX/UI",
  },
  {
    id: 3,
    firstName: "Alexandre",
    lastName: "Moreau",
    birthDate: "2001-11-05",
    email: "alexandre.moreau@ecole.fr",
    major: "Cybersécurité",
  },
  {
    id: 4,
    firstName: "Emma",
    lastName: "Rousseau",
    birthDate: "2003-04-18",
    email: "emma.rousseau@ecole.fr",
    major: "Intelligence Artificielle",
  },
  {
    id: 5,
    firstName: "Lucas",
    lastName: "Leroy",
    birthDate: "2002-09-10",
    email: "lucas.leroy@ecole.fr",
    major: "Développement Web",
  },
  {
    id: 6,
    firstName: "Clara",
    lastName: "Dupont",
    birthDate: "2003-01-25",
    email: "clara.dupont@ecole.fr",
    major: "Marketing Digital",
  },
  {
    id: 7,
    firstName: "Thomas",
    lastName: "Mercier",
    birthDate: "2001-06-30",
    email: "thomas.mercier@ecole.fr",
    major: "Cloud Computing",
  },
  {
    id: 8,
    firstName: "Léa",
    lastName: "Fontaine",
    birthDate: "2003-12-07",
    email: "lea.fontaine@ecole.fr",
    major: "Data Science",
  },
  {
    id: 9,
    firstName: "Nicolas",
    lastName: "Blanc",
    birthDate: "2002-05-14",
    email: "nicolas.blanc@ecole.fr",
    major: "Réseaux et Télécommunications",
  },
  {
    id: 10,
    firstName: "Camille",
    lastName: "Dupuy",
    birthDate: "2003-02-11",
    email: "camille.dupuy@ecole.fr",
    major: "Développement Mobile",
  },
];
